### ISSUE TITLE
pp not working

### ISSUE THREAD

**Issue by dmccarty** [ruby/pp#18]
This is not so much an issue as a plea for help. I upgraded to ruby 3.2.2 and pp no longer works. 
Has anyone reported something like this before or do you know of any potential culprits off the top of your head?

Thank you

**Comment by rubyFeedback** [comment]
pp works for me. Can you be more specific, how does it not work? Can you show sample ruby code? I think people can more easily help you the more they know about the specific issue. For instance, for me pp works fine, 3.2.2 too.

    ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
