### ISSUE TITLE
The result of `pp` is different when overriding `inspect` with `super`

### ISSUE THREAD

**Issue by okuramasafumi** [ruby/pp#9]
```ruby
class C
  def initialize
    @a = 1
    @b = 2
  end
end

pp C.new # => #<C:0x0000000105ad24a0 @a=1, @b=2>
puts C.new.inspect # => #<C:0x0000000105af8dd0 @a=1, @b=2>

class C
  def inspect
    super
  end
end

pp C.new # => #<C:0x0000000105af8588 ...>
puts C.new.inspect # => #<C:0x0000000105af3b00 @a=1, @b=2>
```

Here when we override `inspect` with `super` only code, the result of calling `pp` with an object is different. It looks like calling `inspect` on the object works as expected, is it a bug of `pp`?

**Comment by knu** [comment]
I don't think it's a bug.  pp is about improving the format of the built-in inspect methods and it is part of its job to check if the `inspect` method is redefined.

https://github.com/ruby/pp/blob/f7a794435345f3f4079a0aa85135c27c83032cab/lib/pp.rb#L323-L324

That being said, it's not even pretty_print that generates the `...` part, but Kernel#inspect.

```ruby
class C
  def initialize
    @a = 1
    @b = 2
  end

  def inspect
    super.tap { |s| warn "inspect returns #{s}" }
  end
end

pp C.new
```
Output:
```
inspect returns #<C:0x00007fea17910998 ...>
#<C:0x00007fea17910998 ...>
```

Here's what's happening here.  PP.pp turns on the recursive flag for the `inspect` method on the object and calls the `inspect` method, which then calls super (Kernel#inspect), which in turn detects that the recursive flag for `self` is on and stops further inspection on its instance variables returning a string with the ellipsis.

So, the recursive check is the root of the problem and I'm afraid there is not much that pp can do here.  You probably shouldn't use `super` in your inspect method.

**Comment by okuramasafumi** [comment]
Thank you, now I see it's not a problem about pp.

> You probably shouldn't use super in your inspect method.

I think we don't call `super` in inspect often. I'm closing this but if we face this so many times it might be good to write notes about ``super` in `inspect` somewhere.
